### ISSUE TITLE
Sharing compendium entry in chat is broken when a language other than common is used

### ISSUE THREAD

**Issue by uninvitedguest** [mclemente/fvtt-module-polyglot#279]
**Describe the bug**
When sharing a compendium entry in the chat, instead of sharing the entry the UUID code is translated. This is especially a pain, because we are in a campaign that starts out where few to none of the characters have a shared language.

**To Reproduce**
1. Select a language other than "common"
2. Drag a compendium entry to the chat that you want to share. Hit enter to send.
3. The compendium entry gets translated rather than being a shareable/clickable item.

![image](https://user-images.githubusercontent.com/24210277/218293052-677271e4-3da3-47f7-83c6-a118f6d95774.png)

**Expected behavior**
Expected that the compendium entry would be shared.

![image](https://user-images.githubusercontent.com/24210277/218293075-450b5db5-0b61-4384-8a82-cbff87525e46.png)

 - Game System and version: Pathfinder 2e 4.7.4.
 - Polyglot Version: 1.8.7
 - Are you using Babele? No

**Comment by mclemente** [comment]
Should be fixed now on v1.8.9.

**Comment by uninvitedguest** [comment]
Still occurs on 1.8.9
![image](https://user-images.githubusercontent.com/24210277/218353097-81bc0d01-4687-4cef-9ea3-2860ae02e441.png)
![image](https://user-images.githubusercontent.com/24210277/218353236-78c883be-f2ce-4900-b01f-542cb4de6ff0.png)

**Comment by mclemente** [comment]
Released a fix now. I'm not sure how the last image is possible, it was set to ignore `@UUID` completely.

**Comment by uninvitedguest** [comment]
I'm sorry to say it still persists

![image](https://user-images.githubusercontent.com/24210277/218616100-bb85544d-1729-419c-a14e-36d498907717.png)

![image](https://user-images.githubusercontent.com/24210277/218615921-e9350ab7-8c15-463f-af9f-d9a1260e1661.png)

![image](https://user-images.githubusercontent.com/24210277/218616037-beaf0793-87d1-4d73-98fa-7278cdb420a3.png)

**Comment by mclemente** [comment]
That's on me, I changed the wrong hook 🤦‍♂️
Should actually work now on 1.8.11

**Comment by uninvitedguest** [comment]
Yes! It looks to be working now. Thank you!
