### ISSUE TITLE
Bug regarding Polyglot and PF2E.

### ISSUE THREAD

**Issue by GorodZolotoy** [mclemente/fvtt-module-polyglot#300]
Enabling polyglot using the PF2e system doesn't work as it only displays Ar Ciela texts. No languages show up in the language settings. 
<img width="545" alt="bugreport" src="https://github.com/mclemente/fvtt-module-polyglot/assets/98506009/eabb847a-36db-4a2e-abbc-fa2730f5bf46">

**Comment by mclemente** [comment]
Should be fixed now.

**Comment by lyao6104** [comment]
The fix for this seems to still throw an error on startup in PF2e 5.3.0 (specifically, in the settings menu the language column is still empty, but has default values set):
```
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'rng')
[Detected 1 package: polyglot]
    at pf2eLanguageProvider.getLanguages (LanguageProvider.js:2663:34)
    at setupSteps (LanguageProvider.js:278:15)
    at pf2eLanguageProvider.setup (LanguageProvider.js:309:10)
    at Object.fn (polyglot.js:25:39)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8632:11)
    at async Game._initializeGameView (foundry.js:9908:5)
```
The F12 debug menu seems to think this line is causing problems: 
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/8000674/d027e82a-fbf5-4ce2-837b-a8231b506df9)

**Comment by mclemente** [comment]
Sorry about that. It should be fixed now on v2.0.2
